### ISSUE TITLE
bsuite uninstalls tensorflow-gpu==2.0.0-rc1 when installing baselines via cloned repo

### ISSUE THREAD

**Issue by bionicles** [deepmind/bsuite#10]
this is probably my goof, but i wanted to play with this + baselines so i cloned the repo and installed on ubuntu 16.04, and the step to install baselines overwrote my pip installed tf 2.0.0-rc1

better support for tf2.0 would be awesome, i like the idea of bsuite a lot. Thanks for sharing

**Comment by iosband** [comment]
Hello there!

I'm sorry to hear this happened - installing/managing different TF versions can be a pain.

I actually think that bsuite should have already 100% tf2 support...
But *some* of the baseline agents are implemented in TF1, so we should update the docs here.

We will have a look at updating the instructions/warning in:
https://github.com/deepmind/bsuite/tree/master/bsuite/baselines
But even here there is an example agent using TF2, so it definitely is possible.

Cheers,
Ian
