### ISSUE TITLE
Westworld host attribute matrix

### ISSUE THREAD

**Issue by viliwonka** [deepmind/bsuite#12]
Hi DeepMind.

No issue here; just came here to say that this project scaringly reminds me od Westworlds host attribute matrix 😄 

Even some attributes are similar, such as exploration == curiosity. 

![slika](https://user-images.githubusercontent.com/4028544/65818999-fbed3080-e21f-11e9-8bc9-0c50da3e7631.png)

Cheers!

**Comment by iosband** [comment]
That is funny - and maybe this will give us some more spokes for future bsuite tasks.

For example, could Schmidthuber's formal theory of fun allow us to add a "humour" spoke to the radar plot?
http://people.idsia.ch/~juergen/creativity.html

Thanks for pointing out!
