### ISSUE TITLE
Can't reproduce DQN performance

### ISSUE THREAD

**Issue by SunCherry** [deepmind/bsuite#14]
I noticed you changed the optimizer and some hyper-parameters in DQN compared to those in the "Nature" paper, well, from my side I can't reproduce results by taking any of the two settings, could you share a learning curve of "Breakout"? I have been struggling with the hyper-parameters optimization for two months. Thanks.

**Comment by aslanides** [comment]
Hi there.

This agent is intended to be a simple instantiation of the DQN algorithm (Q-learning + non-linear function approximation + experience replay), and isn't intended to reproduce the Nature Atari results. There are numerous subtleties related to interfacing with Atari (frame stacking, reward clipping, etc) that can be tricky to get right. For agents that are set up to run on Atari, see Dopamine (github.com/google/dopamine) or OpenAI baselines (github.com/openai/baselines)

**Comment by SunCherry** [comment]
> Hi there.
> 
> This agent is intended to be a simple instantiation of the DQN algorithm (Q-learning + non-linear function approximation + experience replay), and isn't intended to reproduce the Nature Atari results. There are numerous subtleties related to interfacing with Atari (frame stacking, reward clipping, etc) that can be tricky to get right. For agents that are set up to run on Atari, see Dopamine (github.com/google/dopamine) or OpenAI baselines (github.com/openai/baselines)

Got it, thanks a lot.
