### ISSUE TITLE
Cannot import Random

### ISSUE THREAD

**Issue by JaroslavVitku** [deepmind/bsuite#17]
After installation, I was getting the 'cannot import Random', there was conflict between your `bsuite/baselines/random/random.py` and system `random.Random` class (as suggested [here](https://stackoverflow.com/questions/25750961/tweepy-importerror-cannot-import-name-random)). After refactoring to `random_baseline.RandomBaseline` everything seems to work.

**Comment by aslanides** [comment]
Hi there! Thanks for the bug report. How are you importing this? If you use absolute imports this should work, i.e.

`from bsuite.baselines.random import random`

**Comment by JaroslavVitku** [comment]
Unfortunately I don't remember exactly how I imported that, but I think I was just running the code from the repo. Anyway, if there are no others with the issue, maybe the problem was on my side, so closing this.
