### ISSUE TITLE
How is the 'generalization' score computed? 

### ISSUE THREAD

**Issue by VincentLiu3** [deepmind/bsuite#19]
In the notebook (bit.ly/bsuite-agents), I only found the description of 6 scores (basis, noise, scale, exploration, memory, and credit assignment). I wonder how is the generalization score computed? Thank you!

**Comment by iosband** [comment]
Each experiment is associated with a different "tag" for the purposes of the spokes.
You can see the TAGS variable in the analysis.py for each experiment.

Then, the score for each spoke is given by the average by each tag:
https://github.com/deepmind/bsuite/blob/master/bsuite/experiments/summary_analysis.py#L163
