### ISSUE TITLE
How to add the results to results.py? What's the results format should be?

### ISSUE THREAD

**Issue by yvxxyh** [deepmind/bsuite#45]
What value should be assigned to “experiments = {}”?

code:
[bsuite/analysis/results.ipynb](https://github.com/deepmind/bsuite/blob/6d8f64997ca256473c3d10be021431facc5a14d7/bsuite/analysis/results.ipynb)

`
#@ title loading results from local data:

experiments = {}  # Add results here

DF, SWEEP_VARS = sqlite_load.load_bsuite(experiments)
`

**Comment by iosband** [comment]
That answer depends on what sort of logging you used to run your experiments...

but, if you did csv logging then it should be the path to the folder where all the csv files are written.

An example is provided in the colab tutorial:
https://colab.sandbox.google.com/drive/1rU20zJ281sZuMD1DHbsODFr1DbASL0RH

Here, we save to `SAVE_PATH_RAND = '/tmp/bsuite/rand'` and that's what you also pass to load the results
