### ISSUE TITLE
Converting Openai gym environments to bsuite environments

### ISSUE THREAD

**Issue by alexminnaar** [deepmind/bsuite#6]
I thought that it might be useful to be able to use openai gym environments within bsuite since there are so many of them.  I noticed that there is a wrapper [here](https://github.com/deepmind/bsuite/blob/master/bsuite/utils/gym_wrapper.py) that converts bsuite environments to openai gym environments, so in my fork I made a reverse wrapper that would convert an openai gym environment to a bsuite environement [here](https://github.com/alexminnaar/bsuite/blob/ce95a2178e010b6ae9acdc16bea09a77f27ce389/bsuite/utils/gym_wrapper.py#L97).  It's pretty untested right now but if you are interested I would be happy to clean it up and make a PR - I think this could be a useful feature.

**Comment by yotam** [comment]
Hi, that's a neat wrapper, would welcome a PR for sure.

**Comment by alexminnaar** [comment]
Thanks @yotam I will clean it up and make a PR.
